---
- name: Deploy Flask App on Localhost
  hosts: local
  become: true

  vars:
    app_dir: /opt/myapp

  tasks:
    - name: Ensure app directory exists
      file:
        path: "{{ app_dir }}"
        state: directory

    - name: Copy app files
      copy:
        src: ./myapp/
        dest: "{{ app_dir }}"
        mode: 0755

    - name: Install requirements
      pip:
        requirements: "{{ app_dir }}/requirements.txt"
        extra_args: --break-system-packages --ignore-installed
        executable: pip3

    - name: Run the Flask app
      shell: |
        FLASK_APP=app.py nohup flask run --host=0.0.0.0 --port=5000 &
      args:
        chdir: "{{ app_dir }}"
